### ISSUE TITLE
Remove Boost.log, because recent Boost versions already have it.

### ISSUE THREAD

**Issue by RubenVerborgh** [ericprud/SWObjects#2]
The current version is difficult to build on systems with more recent versions of Boost, because they already include Boost.Log.

Could the code be removed from this repo, so that the system Boost.Log can be used?

**Comment by ericprud** [comment]
On Mar 9, 2014 2:07 PM, "Ruben Verborgh" notifications@github.com wrote:

> The current version is difficult to build on systems with more recent
> versions of Boost, because they already include Boost.Log.
> 
> Could the code be removed from this repo, so that the system Boost.Log
> can be used?

The API has changed a fair amount. My attempts this far have eliminated
logging altogether. I hope to get to the point where I can commit something
the week after next. If you're keen to fight with this, I can send you what
I've tried so far. There's an idiom in the new API which seems like it
should work but it was commented out in the 1.55 examples.

**Comment by RubenVerborgh** [comment]
Thanks, @ericprud, good to see you're working on this.
Unfortunately, I'm not a C expert myself so it would be better for the library if I don't touch this :-)
I'll wait for your commits;

**Comment by ericprud** [comment]
I should have mentioned this months ago, but this now links against the Boost.Log in boost 1.54 or later.
